### ISSUE TITLE
The library does not seem to work for the first week of the year

### ISSUE THREAD

**Issue by alexdobre** [jsdocker/week-utils#5]
weekUtils.getWeekDate(2020, 1) returns

{
  "weekStart": "2020-12-29T00:00:00.000Z",
  "weekEnd": "2020-01-05T00:00:00.000Z"
}

Both the year and the actual day is wrong.

The answer should be:
{
  "weekStart": "2019-12-30T00:00:00.000Z",
  "weekEnd": "2020-01-05T00:00:00.000Z"
}

**Comment by jsdocker** [comment]
resolved
